### PR TITLE
test against go 1.14.x and go 1.15.x

### PR DESCRIPTION
**Pull request by rickypai**
Hi, I came across this caching solution while researching groupcache, and would like to try this out in a new go project.

PR aside, I'm wondering if this is still used in production at Vimeo or have you settled for another solution? Thanks a lot!

### CODE REVIEW

**Comment by rickypai** [comment]
seems like go 1.9 is failing because its pulling new versions of gRPC which depends on the field `URIs` that was added in go 1.10: https://golang.org/doc/go1.10#crypto/x509

since go 1.9 doesn't support modules, we'd have to revert to some versions of dependency management like vendor directory. would it be ok to drop 1.9? it's been three years and 5 versions since its release

**Comment by dfinkel** [comment]
Thanks for sending this PR!
Yes, we're using this in production at Vimeo.

Yeah, please remove all versions before Go 1.12.

**Comment by rickypai** [comment]
thanks. addressed in https://github.com/vimeo/galaxycache/pull/16/commits/22ce4a537ef15e574e10b892f5282211d6050efb

**Review by dfinkel — APPROVED** [review]
Thanks!

I should probably mention that in production we use a thin wrapper around https://github.com/vimeo/k8swatcher for keeping the peer-list updated (since we run with a kubernetes deployment).

**Comment by rickypai** [comment]
@dfinkel makes sense. it's kind of amusing that everyone runs their own flavor of k8s watchers for service/peer discovery

**Pull request merged**
